services:
  rabbitmq:
    image: rabbitmq:4.2.5-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "${HOST_RABBITMQ_PORT}:5672"
      - "${HOST_RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST} # database, misal user app hanya bisa akses ke vhost myapp
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
