services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - minionet

volumes:
  minio-data:

networks:   
  minionet:

# akses dalam jaringan docker : http://minio:9000
# akses   dalam network yang sama : minionet
