services:
  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "${HOST_REDIS_PORT}:${CONT_REDIS_PORT}"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --save ""
      --appendonly no
      --maxclients 10000
      --timeout 0
      --tcp-keepalive 60
    networks:
      - redis-net

networks:
  redis-net:
    name: redis-net
    driver: bridge
